### ISSUE TITLE
Simpler frontends

### ISSUE THREAD

**Issue by Athas** [melsman/apltail#14]
At the moment, `apltail` is a single program that changes behaviour in response to various command line options.  I find these hard to remember and use, so I suggest the creation of simpler wrapper programs that encapsulate common operations.  For example, I use this `apl2tail` script:

```
#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 <tail program>"
    exit 1
fi

if ! [ "$TAIL_ROOT" ]; then
    echo '$TAIL_ROOT not set - things are unlikely to work' >&2
fi

apl_source=$1
tail_source=${apl_source%.*}.tail

TAIL_PRELUDE=${TAIL_ROOT}/lib/prelude.apl

aplt  -p_types -p_tail -c -o "$tail_source" $TAIL_PRELUDE "$apl_source"
```

**Comment by melsman** [comment]
This script, as well as others, are now available in https://github.com/henrikurms/tail2futhark/tree/master/tools
