### ISSUE TITLE
Make the classic Game of Life example work

### ISSUE THREAD

**Issue by Athas** [melsman/apltail#15]
[This one](https://dfns.dyalog.com/c_life.htm):

```
life←{                                  ⍝ John Conway's "Game of Life".
    ↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵  ⍝ Expression for next generation.
}
```

**Comment by melsman** [comment]
This thing requires nested arrays, which we are not going to support in the short term...

![image](https://cloud.githubusercontent.com/assets/1167803/19840594/ad6f7a7e-9ef9-11e6-848b-f139a5a5ecdb.png)
