### ISSUE TITLE
Make this tiny Mandelbrot work

### ISSUE THREAD

**Issue by Athas** [melsman/apltail#16]
[This one](https://github.com/ngn/apl/blob/master/examples/7-mandelbrot.apl):

```
⎕←' #'[9>|⊃{⍺+⍵*2}/9⍴⊂¯3×.7j.5-⍉a∘.+0j1×a←(⍳n+1)÷n←98]
```

It needs complex numbers.  Not sure what else.

**Comment by Athas** [comment]
Here is one without nested arrays:

```
⎕←' #'[9>|m∘{⍺+⍵*2}⍣9⊢m←¯3×.7j.5-⍉a∘.+0j1×a←(⍳n+1)÷n←98]
```

And one that uses trains:

```
⎕←' #'[9>|m∘(2*⍨+)⍣9⊢m←¯3×.7j.5-⍉a∘.+0j1×a←(⍳n+1)÷n←98]
```

**Comment by Athas** [comment]
(Credit to @arcfide for these.)

**Comment by melsman** [comment]
Do we have a `⎕IO←1` version of this code?

**Comment by Athas** [comment]
No, but does it even do any array indexing?

**Comment by melsman** [comment]
it indexes into the character array ' #' and it uses iota. Fixing these
quickly didn't work, though... Didn't spend a lot of time on this... ;)

Best,

Martin

Den mandag den 31. oktober 2016 skrev Troels Henriksen <
notifications@github.com>:

**Comment by melsman** [comment]
The following version works now (test/mandel.apl):

    ⎕ ← ' #'[1+9>|({m+⍵×⍵}⍣9)(m←¯3×.7j.5-⍉a∘.+0j1×(a←(1+⍳n+1)÷(n←28)))]

Here is the result:

                    #            
                     #           
                   ###           
                   ###           
                ######## #       
                ##########       
               ###########       
          #### ###########       
          ################       
         #################       
    #####################        
         #################       
          ################       
          #### ###########       
               ###########       
                ##########       
                ######## #       
                   ###           
                   ###           
                     #           
                    #            

It also works with tail2futhark...

**Comment by ngn** [comment]
`1+⍳n+1`
I think that should be `¯1+⍳n+1`.
