### ISSUE TITLE
Make this example from Dyalog work

### ISSUE THREAD

**Issue by Athas** [melsman/apltail#18]
https://twitter.com/dyalogapl/status/755706056005877760

```
      {+/,⍵×⍵=+/¨⍳⍴⍵}?5 5⍴10
```

It's a modern version of this piece of ancestor worship: http://keiapl.org/anec/#Dijkstra

**Comment by Athas** [comment]
Hm, the iota creates boxed arrays, doesn't it?

**Comment by Athas** [comment]
Came up with this version.  Not a fan of the duplication:

    {+/+/⍵×⍵=((⍴⍵)⍴⍳1↓⍴⍵)+(⍴⍵)⍴⍳1↑⍴⍵}5 5⍴10

**Comment by melsman** [comment]
The following works in apltail:

````
{+/+/⍵×⍵=((⍴⍵)⍴⍳⊃⍴⍵)+(⍴⍵)⍴⍳⊃⍴⍵}5 5⍴10
````
The original version requires nested arrays and we require iota to take a scalar argument.
