### ISSUE TITLE
Support simple conditionals

### ISSUE THREAD

**Issue by dybber** [melsman/apltail#6]
For the pricer we need conditionals of the form:

mins[1] ≥ 1: return ← 1150.0 × md_disc[1]

See https://github.com/dybber/aplbench/blob/master/finpar-generic-pricer/dyalog/pricer.apl#L174

We might want to simplify the above example code before working more on this

**Comment by melsman** [comment]
Does this mean that we also need support for explicit assignment and not just let-binding support that we have now? Would it be ok with a plan for implementing index-assignment but not variable assignment?

**Comment by melsman** [comment]
BTW: We do have support for conditionals already - see the else.apl test examples.
